### ISSUE TITLE
能给个使用文档吗

### ISSUE THREAD

**Issue by fulaoaz** [ys928/XunYou#1]
有点没搞明白怎么使用

**Comment by fulaoaz** [comment]
不会用bzip2压缩qwq，能不能直接支持txt阅读呢

**Comment by ys928** [comment]
> 不会用bzip2压缩qwq，能不能直接支持txt阅读呢

嗯……后面有时间应该会支持，暂时可以先使用我刚刚上传的一个bzip2.exe将对应的txt文件直接转换为对应的格式（注意txt一定要是utf-8编码，换行符为CRLF，否则会出现意想不到的bug）

window记事本可以查看txt文本的格式：
![image](https://github.com/ys928/XunYou/assets/80371119/3f7741d4-615e-4567-95d5-b4dba4a97c94)

**Comment by fulaoaz** [comment]
okok，谢谢大佬
