### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fulaoaz** [ys928/XunYou#2]
建议加一个自定义调整什么的，当然如果能加上目录啊，书签啊，那就更好了

**Comment by ys928** [comment]
1.自定义调整什么？

2.由于是txt文本格式小说，很多小说的标题格式不统一（比如有的是第一章、有的是第一幕、序章，等等），所以将这个功能调整为了行数，可以通过ctrl+g进行跳转，右下角展示的就是：当前行数/总行数

3.书签这个功能确实不错，后面我有时间会实现的

当然如果你有更好的想法也可以提出来

**Comment by fulaoaz** [comment]
自定义调整：建议参考一下https://reader.htmake.com/#/reader
这是一个开源项目，他的这个自定义调整感觉做的很好
![image](https://github.com/ys928/XunYou/assets/89621766/eb095103-e3d4-49d1-9369-8bd7db63eb7b)
![image](https://github.com/ys928/XunYou/assets/89621766/55eed941-cc2f-4426-95e0-491f056c78fd)

一直用这个，但是它阅读本地小说不是很方便，它这个Windows版感觉做的不怎么好，就只想是简单的网页应用化


关于目录这个，你也可以参考一下其他开源项目的目录规则

**Comment by fulaoaz** [comment]
而且我发现，你的这个阅读器会记载阅读到了那里，再次到开始会自动总上次阅读的位置打开，但同时也发现了，它无法用滚轮回滚到之前阅读到的地方，只能通过Ctrl+G跳转

**Comment by fulaoaz** [comment]
如果目录实现了，最好再加一个下一章/下一页等按键会方便很多，标题什么的要是能自动加粗加大也是很好的

**Comment by fulaoaz** [comment]
大佬可以参考一下这两个项目
https://github.com/hectorqin/reader
https://github.com/troyeguo/koodo-reader

**Comment by ys928** [comment]
ok

**Comment by fulaoaz** [comment]
新版挺好的，就是目录能不能加个倒序和搜索，还有就是这个提示
![image](https://github.com/ys928/XunYou/assets/89621766/d11bba83-711f-48fa-9936-b4fc8c1bd524)
能不能在打开小说后，做个具体案件，有时候忘了按键，只能退出软件重进

**Comment by fulaoaz** [comment]
而且虽然支持了txt格式的阅读，但是从软件内选择文件夹，仍然只能识别到.novel格式的小说，txt格式的只能靠自己拖入软件进行阅读，拖入软件后，它也只是能阅读，但没有加入那个搜索栏里面（应该算是书架？不知道你设计的这个搜索栏算不算书架），同时在阅读A小说时，切换到另一本小说B，再次点击目录，你会发现目录仍然是A小说的目录，但是你点击此时目录A小说的某一章节时，跳转的是B对应的章节，功能没有问题，所以只是显示出了问题

**Comment by fulaoaz** [comment]
目录的那个问题，似乎是只会显示你打开软件后第一次点击目录是阅读的小说的目录，后面切换小说也不会变

**Comment by ys928** [comment]
ok，bug已修复，其它功能后面有时间再添加

**Comment by fulaoaz** [comment]
端午还逛Github啊，端午快乐！

**Comment by ys928** [comment]
端午快乐（因为提交issue会给我发邮件的，看到了就来逛逛）

**Comment by fulaoaz** [comment]
刚才偶然触发了一个BUG，就是暗夜模式和白天模式只作用在小说界面，但是没有作用到边框部分，就是边框和小说界面暗夜和白天模式恰好相反，退出软件后，再次进入想着再去触发一下，没触发成功，应该是意外

**Comment by fulaoaz** [comment]
![image](https://github.com/ys928/XunYou/assets/89621766/4ad2e1b6-ccc7-4471-852c-f413e2d55d1d)

![image](https://github.com/ys928/XunYou/assets/89621766/a6ea0e44-1700-4195-8fcd-fff75bec7d4f)

**Comment by fulaoaz** [comment]
应该算是意外吧，再次退出软件，再次打开，就触发了

**Comment by fulaoaz** [comment]
真成意外了，我现在每次打开软件，都是这样了...

**Comment by fulaoaz** [comment]
而且我发现，现在那个搜索栏，退出似乎不会记录了，每次进入都有重新选择文件夹读取

**Comment by fulaoaz** [comment]
> 真成意外了，我现在每次打开软件，都是这样了...

又恢复了

**Comment by fulaoaz** [comment]
历史记录应该一切正常

> 而且我发现，现在那个搜索栏，退出似乎不会记录了，每次进入都有重新选择文件夹读取

**Comment by ys928** [comment]
C:\Users\你的用户名\AppData\Roaming\XunYou

自己维护一个ui库太累了，所以新版本用的一个开源ui库，目前配置可能还没调好，可以删除上面这个路径的文件夹试一试

**Comment by fulaoaz** [comment]
试过了，似乎还是会出现这种问题

> ![image](https://user-images.githubusercontent.com/89621766/247832824-4ad2e1b6-ccc7-4471-852c-f413e2d55d1d.png)
> 
> ![image](https://user-images.githubusercontent.com/89621766/247832856-a6ea0e44-1700-4195-8fcd-fff75bec7d4f.png)

**Comment by ys928** [comment]
有点神奇，我试了几遍也没触发成功……等我有空再看看代码吧，目前确实还没有完全适配完成

**Comment by fulaoaz** [comment]
好好过节吧，上学去了qwq

**Comment by fulaoaz** [comment]
强烈建议加个书架，搜索栏读取目录那个，退出软件不会留存记忆，如果要打开新的小说阅读，必须再次读取目录，当然已经阅读的小说，在历史记录里面有显示，那个主题的问题已经恢复了

**Comment by ys928** [comment]
已修复不显示上一次目录的bug。

这只是一个小巧的阅读小说的软件，加书架暂时来说没多大意义，也没有书源。
