### ISSUE TITLE
目录识别规则有问题

### ISSUE THREAD

**Issue by fulaoaz** [ys928/XunYou#8]
![image](https://github.com/ys928/XunYou/assets/89621766/52d83970-d64e-45cc-afa8-da15daf4acd8)

这都是校对好的文本，章节名称没问题，应该shi是识别规则的问题

**Comment by ys928** [comment]
应该是某些章节标题的名字太长，因为我设置的最多10个字符，现在已经重新修改了识别标题规则，你再试试看

**Comment by fulaoaz** [comment]
ok了
